# Generated by Django 5.2.6 on 2025-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='links',
            field=models.CharField(default=1, max_length=555),
            preserve_default=False,
        ),
    ]
