# Generated by Django 5.2.6 on 2025-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0002_projects_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
