# Generated by Django 5.2.6 on 2025-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0003_projects_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='empollyDeatiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=225)),
                ('Eemail', models.EmailField(max_length=255)),
                ('phone', models.IntegerField()),
                ('Eid', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=255)),
                ('empollyPosition', models.CharField(max_length=255)),
            ],
        ),
    ]
