# Generated by Django 5.2.6 on 2025-09-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0004_empollydeatiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='empollydeatiles',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
