# Generated by Django 5.2.6 on 2025-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0005_empollydeatiles_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=555)),
                ('phone', models.IntegerField(unique=True)),
                ('Iid', models.CharField(max_length=100, unique=True)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='empollydeatiles',
            name='Eemail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empollydeatiles',
            name='Eid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='empollydeatiles',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
