# Generated by Django 5.2.7 on 2025-10-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0006_interns_alter_empollydeatiles_eemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empollydeatiles',
            name='propic',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
