# Generated by Django 5.2.7 on 2025-10-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0007_empollydeatiles_propic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empollydeatiles',
            name='empollyPosition',
        ),
        migrations.AlterField(
            model_name='empollydeatiles',
            name='roll',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('UXI Developer', 'UXI Developer')], max_length=255),
        ),
    ]
