# Generated by Django 5.2.7 on 2025-10-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0009_projectsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_member', to='krifyBackend.empollydeatiles')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team', to='krifyBackend.projectsinfo')),
            ],
        ),
    ]
