# Generated by Django 5.2.7 on 2025-10-11 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0010_projectteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='empollydeatiles',
            name='experience',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)]),
            preserve_default=False,
        ),
    ]
