# Generated by Django 5.2.7 on 2025-10-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0011_empollydeatiles_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='empollydeatiles',
            name='currentProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assend_employee', to='krifyBackend.projects'),
        ),
        migrations.AlterField(
            model_name='projectteams',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team', to='krifyBackend.projects'),
        ),
    ]
