# Generated by Django 5.2.6 on 2025-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0012_empollydeatiles_currentproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empollydeatiles',
            name='previousProjects',
            field=models.ManyToManyField(blank=True, related_name='previous_employees', to='krifyBackend.projects'),
        ),
    ]
