# Generated by Django 5.2.6 on 2025-10-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0013_empollydeatiles_previousprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteams',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
