# Generated by Django 5.2.6 on 2025-10-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0014_projectteams_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectteams',
            old_name='status',
            new_name='proStatus',
        ),
    ]
