# Generated by Django 5.2.6 on 2025-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0015_rename_status_projectteams_prostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='propic',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interns',
            name='course',
            field=models.CharField(choices=[('WEB Frontend', 'CEO'), ('HR', 'HR'), ('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('UXI Developer', 'UXI Developer')], max_length=255),
        ),
    ]
