# Generated by Django 5.2.6 on 2025-10-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0016_interns_propic_alter_interns_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interns',
            name='course',
            field=models.CharField(choices=[('WEB Frontend', 'Web Frontend'), ('Python Fullstack', 'Python Fullstack'), ('Flutter', 'Fultter'), ('AI & ML', 'AI & ML'), ('UIX', 'UIX')], max_length=255),
        ),
    ]
