# Generated by Django 5.2.6 on 2025-10-17 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0018_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
