# Generated by Django 5.2.6 on 2025-10-17 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krifyBackend', '0019_alter_projects_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendance',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('On Leave', 'On Leave')], default='Absent', max_length=20),
        ),
        migrations.CreateModel(
            name='InternAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('On Leave', 'On Leave')], default='Absent', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_attendance', to='krifyBackend.interns')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('intern', 'date')},
            },
        ),
    ]
